SELECT DISTINCT
    TRIM(F1_FILIAL) AS FILIAL,
    TRIM(C7_NUM) AS PEDIDO,
    TRIM(SYS_USR1.USR_NOME) AS "USUARIO_PEDIDO",
    TRIM(C7_EMISSAO) AS "EMISSAO_PEDIDO",
    TRIM(F1_DOC) AS NOTA,
    TRIM(F1_SERIE) AS SERIE,
    TRIM(F1_EMISSAO) AS "EMISSAO_NF",
    TRIM(A2_COD) AS COD_FORNECEDOR,
    TRIM(A2_NOME) AS FORNECEDOR,
    TRIM(A2_LOJA) AS LOJA,
    TRIM(F1_DTLANC) AS "DATA_CLASSIFICACAO",
    SF1.R_E_C_N_O_ AS "REC_F1",
    TRIM(SE2.E2_PARCELA) AS "NUMERO_PARCELA",
    TRIM(SE2.E2_VENCTO) AS "VENCIMENTO",
    TRIM(SE2.E2_BAIXA) AS "DATA_BAIXA",
    TRIM(Z05_CAMPO) AS "CAMPO",
    TRIM(Z05_VALATU) AS "OBSERVACAO_HISTORICO",
    TRIM(SYS_USR3.USR_NOME) AS "USUARIO_HISTORICO",
    TRIM(Z05_DATA) AS "DATA_HISTORICO",
    TRIM(Z05_HORA) AS "HORA_HISTORICO"
FROM
    SF1010 SF1
        INNER JOIN SD1010 SD1 ON SD1.D1_FILIAL = SF1.F1_FILIAL
        AND SD1.D1_DOC = SF1.F1_DOC
        AND SD1.D1_SERIE = SF1.F1_SERIE
        AND SD1.D1_FORNECE = SF1.F1_FORNECE
        AND SD1.D1_LOJA = SF1.F1_LOJA
        AND SD1.D_E_L_E_T_ = ''
        LEFT JOIN SC7010 SC7 ON SC7.C7_FILIAL = SD1.D1_FILIAL
        AND SC7.C7_NUM = SD1.D1_PEDIDO
        AND SC7.C7_ITEM = SD1.D1_ITEMPC
        AND SC7.C7_PRODUTO = SD1.D1_COD
        AND SC7.D_E_L_E_T_ = ''
        LEFT JOIN SYS_USR SYS_USR1 ON SC7.C7_USER = SYS_USR1.USR_ID
        AND SYS_USR1.D_E_L_E_T_ = ''
        LEFT JOIN SA2010 SA2 ON SF1.F1_FORNECE = SA2.A2_COD
        AND SF1.F1_LOJA = SA2.A2_LOJA
        AND SA2.D_E_L_E_T_ = ''
        LEFT JOIN SYS_USR SYS_USR2 ON UPPER(TRIM(SF1.F1_XUSRRA)) = UPPER(SYS_USR2.USR_CODIGO)
        AND SYS_USR2.D_E_L_E_T_ = ''
        LEFT JOIN Z05010 Z05 ON SF1.R_E_C_N_O_ = Z05.Z05_CHAVE
        AND Z05.Z05_FILIAL = SF1.F1_FILIAL
        AND Z05.Z05_ROTINA = 'RODOAPP'
        AND Z05.D_E_L_E_T_ = ''
        LEFT JOIN SYS_USR SYS_USR3 ON UPPER(TRIM(Z05.Z05_USER)) = UPPER(SYS_USR3.USR_CODIGO)
        AND SYS_USR3.D_E_L_E_T_ = ''
        LEFT JOIN SE2010 SE2 ON E2_FILIAL = F1_FILIAL
        AND E2_NUM = F1_DOC
        AND E2_PREFIXO = F1_SERIE
        AND E2_FORNECE = F1_FORNECE
        AND E2_LOJA = F1_LOJA
        AND SE2.D_E_L_E_T_ = ''
WHERE
    F1_TIPO <> 'D'
    AND SF1.D_E_L_E_T_ = ''
    AND F1_XUSRRA <> ''
    AND SF1.R_E_C_N_O_ = @rec_f1
ORDER BY
    SF1.R_E_C_N_O_ DESC;
